models:
  # Part 1: SFT vs. RL

  # SFT Distilled Models
  
  # SFT + RL models
        
  # Part 2: LIMO Hypothesis
  # LIMO models

  # LIMO + MATH8k QwQ

  # Part 3: Different Teacher Models
  # AM-Distill-Qwen-32B Teacher
  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-AM-Distill-Qwen-32B-16k-5epochs-2e-5lr-step100"
  #   nick_name: "Qwen2.5-3B-math8k-AM-distill-step100"

  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-AM-Distill-Qwen-32B-16k-5epochs-2e-5lr-step200"
  #   nick_name: "Qwen2.5-3B-math8k-AM-distill-step200"

  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-AM-Distill-Qwen-32B-16k-5epochs-2e-5lr-step300"
  #   nick_name: "Qwen2.5-3B-math8k-AM-distill-step300"

  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-AM-Distill-Qwen-32B-16k-5epochs-2e-5lr-step400"
  #   nick_name: "Qwen2.5-3B-math8k-AM-distill-step400"

  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-AM-Distill-Qwen-32B-16k-5epochs-2e-5lr-step500"
  #   nick_name: "Qwen2.5-3B-math8k-AM-distill-step500"

  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-AM-Distill-Qwen-32B-16k-5epochs-2e-5lr-step550"
  #   nick_name: "Qwen2.5-3B-math8k-AM-distill-step550"

  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-AM-Distill-Qwen-32B-16k-5epochs-2e-5lr-step600"
  #   nick_name: "Qwen2.5-3B-math8k-AM-distill-step600"

  # Qwen3-32B Teacher
  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-Qwen3-32B-16k-5epochs-2e-5lr-step100"
  #   nick_name: "Qwen2.5-3B-math8k-Qwen3-distill-step100"

  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-Qwen3-32B-16k-5epochs-2e-5lr-step200"
  #   nick_name: "Qwen2.5-3B-math8k-Qwen3-distill-step200"
  
  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-Qwen3-32B-16k-5epochs-2e-5lr-step300"
  #   nick_name: "Qwen2.5-3B-math8k-Qwen3-distill-step300"
  
  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-Qwen3-32B-16k-5epochs-2e-5lr-step400"
  #   nick_name: "Qwen2.5-3B-math8k-Qwen3-distill-step400"
  
  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-Qwen3-32B-16k-5epochs-2e-5lr-step500"
  #   nick_name: "Qwen2.5-3B-math8k-Qwen3-distill-step500"

  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-Qwen3-32B-16k-5epochs-2e-5lr-step550"
  #   nick_name: "Qwen2.5-3B-math8k-Qwen3-distill-step550"

  - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-Qwen3-32B-16k-5epochs-2e-5lr-step600"
    nick_name: "Qwen2.5-3B-math8k-Qwen3-distill-step600"

  # # QwQ-32B Teacher
  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-QwQ-32B-16k-5epochs-2e-5lr-step100"
  #   nick_name: "Qwen2.5-3B-math8k-QwQ-distill-step100"

  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-QwQ-32B-16k-5epochs-2e-5lr-step200"
  #   nick_name: "Qwen2.5-3B-math8k-QwQ-distill-step200"

  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-QwQ-32B-16k-5epochs-2e-5lr-step300"
  #   nick_name: "Qwen2.5-3B-math8k-QwQ-distill-step300"

  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-QwQ-32B-16k-5epochs-2e-5lr-step400"
  #   nick_name: "Qwen2.5-3B-math8k-QwQ-distill-step400"

  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-QwQ-32B-16k-5epochs-2e-5lr-step500"
  #   nick_name: "Qwen2.5-3B-math8k-QwQ-distill-step500"

  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-QwQ-32B-16k-5epochs-2e-5lr-step550"
  #   nick_name: "Qwen2.5-3B-math8k-QwQ-distill-step550"

  # - model_name: "aochongoliverli/Qwen2.5-3B-math8k-distill-QwQ-32B-16k-5epochs-2e-5lr-step600"
  #   nick_name: "Qwen2.5-3B-math8k-QwQ-distill-step600"